apiVersion: capabilities.3scale.net/v1beta1
kind: ProxyConfigPromote
metadata:
  name: camel-quarkus-datagrid-tester-service
spec:
  deleteCR: true
  productCRName: camel-quarkus-datagrid-tester-service
  production: true