---
apiVersion: v1
kind: Secret
metadata:
  name: test-account-user-secret
stringData:
  password: openshift
type: Opaque
---
apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: test-account
spec:
  orgName: Test Account
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: test-account-user
spec:
  developerAccountRef:
    name: test-account
  email: jnyilimb+testaccount@redhat.com
  passwordCredentialsRef:
    name: test-account-user-secret
  role: admin
  username: testaccountadmin
---
kind: Application
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: test-account-application
spec:
  accountCR:
    name: test-account
  applicationPlanName: basic-plan
  description: 'Test Account application for the Camel Quarkus & Datagrid Tester Service'
  name: Test Account App
  productCR:
    name: camel-quarkus-datagrid-tester-service