---
apiVersion: v1
kind: Secret
metadata:
  name: quarkus-opentracing-endpoint-secret
stringData:
  quarkus.jaeger.endpoint: "http://jaeger-all-in-one-inmemory-collector.ceq-services-jvm.svc:14268/api/traces"
type: Opaque