# Configuration file

# Camel
camel:
    context:
        name: camel-quarkus-jsonvalidation-api

# Quarkus
quarkus:
    banner:
        enabled: true
    ssl:
        native: true

    ## Quarkus OpenShift extension configuration for S2I binary workflow builds
    kubernetes-client:
        trust-certs: true
    s2i:
        base-jvm-image: registry.access.redhat.com/ubi8/openjdk-11
        base-native-image: quay.io/quarkus/ubi-quarkus-native-binary-s2i:1.0
    openshift:
        expose: true
        replicas: 2
        # liveness-probe:
        #     http-action-path: /health/live
        #     initial-delay: 0
        #     period: 30
        # readiness-probe:
        #     http-action-path: /health/ready
        #     initial-delay: 0
        #     period: 30

    ## Quarkus native build 
    native:
        # If all character sets should be added to the native image. This increases image size
        add-all-charsets: true
        # The docker image to use to do the image build
        builder-image: registry.access.redhat.com/quarkus/mandrel-20-rhel8:20.1

    ## Camel Quarkus
    camel:
        # Microprofile Camel Health checks
        # Cf. https://camel.apache.org/camel-quarkus/latest/extensions/microprofile-health.html
        health:
            enabled: true

        # Microprofile Camel Metrics
        # Cf. https://camel.apache.org/camel-quarkus/latest/extensions/microprofile-metrics.html
        metrics:
            enable-route-policy: true
            enable-message-history: false
            enable-exchange-event-notifier: true
            enable-route-event-notifier: true
            enable-camel-context-event-notifier: true

        # native mode configuration
        native:
            # A comma separated list of Ant-path style patterns to match class names
            # that should be registered for reflection.
            # Reference: https://camel.apache.org/camel-quarkus/latest/user-guide/native-mode.html#reflection
            reflection:
                include-patterns: java.lang.Exception,org.apache.camel.component.jsonvalidator.JsonValidationException

            # A comma separated list of Ant-path style patterns to match resources
            # that should be <strong>included</strong> in the native executable. By default,
            # resources not selected by quarkus itself are ignored. Then, inclusion
            # of additional resources could be triggered with
            # <code>includePatterns</code>. When the inclusion patterns is too
            # large, eviction of previously selected resources could be triggered
            # with <code>excludePatterns</code>.
            resources:
                include-patterns: json-schema/*,openapi/*

    # Register for indexing
    # Reference: https://camel.apache.org/camel-quarkus/latest/user-guide/native-mode.html#reflection
    index-dependency:
        jsonvalidator:
            group-id: org.apache.camel.quarkus
            artifact-id: camel-quarkus-json-validator