---
plan:
  name: Basic
  state: published
  setup_fee: 0.0
  cost_per_month: 0.0
  trial_period_days: 0
  approval_required: false
  default: false
  system_name: basic_plan
limits:
- period: minute
  value: 10
  metric_system_name: getfruits
- period: minute
  value: 10
  metric_system_name: addfruit
- period: minute
  value: 10
  metric_system_name: getlegumes
pricingrules: []
plan_features:
- name: 'Free'
  system_name: free
  scope: application_plan
  visible: true
  description: 'Free'
- name: 'Limited calls'
  system_name: limited_calls
  scope: application_plan
  visible: true
  description: 'Limited calls'
metrics: []
methods:
- name: getfruits
  system_name: getfruits
  friendly_name: getFruits
  description: Returns a list of hard-coded and added fruits
- name: addfruit
  system_name: addfruit
  friendly_name: addFruit
  description: Adds a fruit in the hard-coded list
- name: getlegumes
  system_name: getlegumes
  friendly_name: getLegumes
  description: Returns a list of hard-coded legumes